jquery/ci-management

- .gitignore
- .pre-commit-config.yaml
- .yamllint.conf
- INFO.yaml
- README.md
- tox.ini
> Setup repo administrative files

- .gitmodules
- packer/README.md
- packer/provision/local-builder.yaml
- packer/templates/builder.json
> Setup common-packer and initial builder

- .gitmodules
> Add global-jjb

- .gitmodules
- jjb/global-jjb/jenkins-init-scripts
- jjb/global-jjb/jjb
- jjb/global-jjb/shell
Configure global-jjb and symlinks
> Configure global-jjb

- jjb/defaults.yaml
> Fix the GitHub/Jenkins SSH key

- jjb/ci-management/ci-packer.yaml
Adding packer jobs for CentOS-7
> Add packer jobs

- jjb/ci-management/ci-jobs.yaml
- jjb/defaults.yaml
> Set Stream to main

- jenkins-config/global-vars-production.sh
Add new Jenkins global environment variables required for log shipping
> Add global variables for log shipping

- jenkins-config/global-vars-production.sh
> Fix Nexus var

- jjb/ci-management/ci-jobs.yaml
> Upgrade JJB version to 3.5.0

- jjb/defaults.yaml
> Modifying build retention default

- jjb/ci-management/ci-packer.yaml
> Build common-packer images

- packer/provision/local-docker.yaml
- packer/templates/docker.json
Setting up common-packer docker template
> Setup Docker template

- jjb/ci-management/ci-packer.yaml
Removing images that aren't needed by the community.
> Remove images

- packer/provision/local-builder.yaml
Adding tasks to install nodejs on CentOS images
> Add tasks to install nodejs

- packer/provision/local-builder.yaml
> Centos image with NodeJs support

- packer/provision/local-builder.yaml
Fixing pre-requisite package g++ to gcc-c++.
> Fixing pre-requisite package g++ to gcc-c++

- jjb/ci-management/ci-jobs.yaml
> Fix jenkins views

- jenkins-config/clouds/openstack/cattle/centos7-v3-builder-1c-1g.cfg
> Add V3 flavor for testing

- jjb/ci-management/ci-packer.yaml
> Modify Packer jobs to use new template

- packer/provision/local-builder.yaml
Signed-off-by: Chandra Dasari <cdasari@contractor.linuxfoundation.org>
> Fixing sudo issue.

- jenkins-config/clouds/openstack/cattle/centos7-builder-2c-2g.cfg
- jenkins-config/clouds/openstack/cattle/cloud.cfg
> Modify builders to use the new CentOS image

- .pre-commit-config.yaml
- jjb/jquery/jquery-core.yaml
> Add JQuery Core job

- jjb/jquery-color/jquery-color.yaml
- jjb/jquery-core/jquery-core.yaml
- jjb/jquery-migrate/jquery-migrate.yaml
- jjb/jquery-ui/jquery-ui.yaml
Adding JQuery projects and basic shell for configuring jobs
> Add JQuery projects

- jjb/jjb-templates/jq-core-jobs.yaml
- jjb/jquery-core/jquery-core.yaml
- jjb/shell/jquery-core-build.sh
> CI: Add JQuery Core job template

- jjb/shell/jquery-core-build.sh
fixing git commit config issue
Signed-off-by: Chandra Dasari <cdasari@contractor.linuxfoundation.org>
> testing git commit issue jquery core job

- jjb/jjb-templates/jq-core-jobs.yaml
- jjb/shell/jquery-core-build.sh
> Fix: JQuery Core verify and merge job failures

- jjb/jjb-templates/README.md
Signed-off-by: Chandra Dasari <cdasari@contractor.linuxfoundation.org>
> Feat: Adding JQuery Core job template Readme

- jenkins-config/managed-config-files/custom/packer-cloud-env/content
Signed-off-by: Vanessa Valderrama <vvalderrama@linuxfoundation.org>
> Chore: Fix cloud_env syntax

- jenkins-config/managed-config-files/custom/packer-cloud-env/content
Signed-off-by: Andrew Grimberg <agrimberg@linuxfoundation.org>
> Fix: Correct password token for packer

- packer/provision/local-builder.yaml
Correcting synxtax errors causing build failures
Signed-off-by: Vanessa Valderrama <vvalderrama@linuxfoundation.org>
> Fix: Correct syntax errors
